services:
  auth:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8080"
      - "5005:5005"
    command: [ "dotnet", "Api.dll", "--no-build", "--additional-deps", "Docker" ]