services:
  room:
    image: ${DOCKER_REGISTRY-}room
    build:
      context: .
      dockerfile: Api/Dockerfile
    networks:
      - def

networks:
  def:
    external: true
    name: Team8-network